### ISSUE TITLE
Response from Dictionary According to Language Selection

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/DictionaryLookup#1]
#### Using this video:

http://ayamel.byu.edu/course/15/content/883
#### Referencing this phrase in that video:

Вегетарианский пудинг в 1900. Печь можете запускать по моей команде.
#### With language for definitions set to "English" and looking up the word:

можете 
#### This definition is returned from SeaLang:

![image](https://cloud.githubusercontent.com/assets/7268293/5288867/1c1124f2-7af6-11e4-8842-e599327713dc.png)
#### When I  change the language for definitions to "Russian" and look up the same word, this definition is returned from Ayamel:

![image](https://cloud.githubusercontent.com/assets/7268293/5288944/d229d680-7af6-11e4-9890-181e7ea16749.png)

**Comment by gliese1337** [comment]
As far as I can tell, this is an error in the SeaLang dictionary.
